############################################
# APP
############################################
spring.application.name=indexador
server.port=8081

############################################
# DATASOURCE (PostgreSQL)
############################################
spring.datasource.url=jdbc:postgresql://localhost:5432/postgres
spring.datasource.driver-class-name=org.postgresql.Driver
 spring.datasource.username=postgres
spring.datasource.password=admin

############################################
# JDBC
############################################
spring.jdbc.template.fetch-size=100

############################################
# SPRING BATCH
############################################
# Siempre inicializa metadata de batch
spring.batch.jdbc.initialize-schema=always

# Evita que el job corra automáticamente al levantar la app
spring.batch.job.enabled=false

############################################
# LOGGING
############################################
logging.level.root=INFO
logging.level.org.springframework.batch=INFO
logging.level.com.pdf.indexador=DEBUG

############################################
# PDF INDEXADOR (custom)
############################################
# Carpeta donde están los PDFs
indexador.pdf.input-folder=archivos

# Tamaño de chunk de texto (si lo usas en el processor)
indexador.pdf.chunk-size=500

############################################
# JPA (NO USAMOS JPA, pero evita warnings)
############################################
spring.jpa.open-in-view=false

spring.batch.job.name=pdfJob
spring.batch.schema=classpath:org/springframework/batch/core/schema-postgresql.sql